apiVersion: apps/v1
kind: Deployment
metadata:
  name: checke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checke
  template:
    metadata:
      labels:
        app: checke
    spec:
      imagePullSecrets:
      - name: manauthc
      containers:
      - name: checke-container
        image: checklistcr.azurecr.io/auditchecklistmicroservice:latest
        imagePullPolicy : Always
        env:
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: checke-service
spec:
  type: LoadBalancer
  ports:
  - port : 80
  selector:
    app: checke